name: epub
version: 1.2.9
author: Colin Nelson <colinnlsn@gmail.com>
description: Epub Parser for Dart. Suitable for use on the Web or in Flutter 
homepage: https://github.com/orthros/dart-epub
environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
dependencies:
  async: "^2.0.8"
   archive: "^2.0.11"
   xml: "^3.4.0"
   image: "^2.0.7"
dev_dependencies:
  test: "^0.12.0"
  path: "^1.5.1"
